# Generated by Django 2.2.24 on 2021-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
